# Generated by Django 5.0.6 on 2024-07-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
